version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-32023}:${PORT:-32023}"  # Settings App Web UI
      - "8384:8384"  # Syncthing Web UI
    volumes:
      - manga_sync:/sync:rw    # Syncthing data - managed by Docker
      - app_data:/app/data:rw  # App settings and config - managed by Docker
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
      - ST_HOME=/app/data/syncthing
      # Import variables from .env file
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - KINDLE_EMAIL=${KINDLE_EMAIL}
      - PORT=${PORT:-32023}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped

volumes:
  manga_sync:  # Docker-managed volume for synced files
  app_data:    # Docker-managed volume for app data and settings